name: maven build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: git clone
        run: git clone https://github.com/apache/guacamole-client.git

     
      - name: Run a multi-line script
        run: |
          cd guacamole-client
          mvn package
          cd guacamole/target/
          ls 
          

          
          
