name: maven build
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking repo
        uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        
        
      - name: awsCLI
        uses: unfor19/install-aws-cli-action@v1

      - name: git clone
        run: git clone https://github.com/apache/guacamole-client.git

     
      - name: Run a multi-line script
        run: |
          cd guacamole-client
          mvn package
          cd guacamole/target/
          aws s3 cp guacamole-1.5.2.war s3://guacamole-client/
          aws s3 cp --recursive guacamole-1.5.2 s3://guacamole-client/guacamole
          

          
          
